### ISSUE TITLE
Modernize codebase to take advantage of node.js 22(lts)

### ISSUE THREAD

**Issue by billchurch** [billchurch/webssh2#383]
## Overview
This issue outlines the plan to upgrade the WebSSH2 server from Node.js v6.9.1 to v22.12.0 LTS. This modernization will improve code quality, reduce dependencies, and leverage modern Node.js features.

### Key Dependencies to Update
- `socket.io@2.2.0` → Latest (`socket.io@4.x`)
- `ssh2@0.8.9` → Latest (`ssh2@1.x`)
- `express@4.14.1` → Latest (`express@4.x`)
- `ajv@4.11.8` → Latest (`ajv@8.x`)
- Test framework: Currently using Jest v21.2.1

### Code Patterns Needing Modernization
1. Callback-based patterns in:
   - `ssh.js`: SSH connection handling
   - `socket.js`: Socket.IO event handling
   - `middleware.js`: Express middleware
   - File operations in multiple modules

2. CommonJS require statements throughout:
   ```javascript
   const SSH = require('ssh2').Client
   const EventEmitter = require('events')
   ```

3. Older error handling patterns:
   ```javascript
   // Current pattern in ssh.js
   this.conn.on('error', err => {
     if (this.authAttempts < DEFAULTS.MAX_AUTH_ATTEMPTS) {
       // ... callback handling
     }
   })
   ```

### Phase 1: Development Environment Setup
- [ ] Update Node.js version requirement in `package.json`
- [ ] Add `.nvmrc` file with Node.js 22.12.0
- [ ] Update ESLint configuration for modern JavaScript
- [ ] Add TypeScript configuration
- [ ] Update test runner configuration
- [ ] Add GitHub Actions for automated testing

### Phase 2: Dependencies Update
- [ ] Update core dependencies:
  ```diff
  {
    "dependencies": {
  -   "socket.io": "~2.2.0",
  +   "socket.io": "^4.7.4",
  -   "ssh2": "~0.8.9",
  +   "ssh2": "^1.15.0",
  -   "express": "^4.14.1",
  +   "express": "^4.18.2",
  -   "ajv": "^4.11.8",
  +   "ajv": "^8.12.0"
    }
  }
  ```
- [ ] `webssh2_client` package `socket.io-client` module to  `4.7.4` [webssh2_client 8](https://github.com/billchurch/webssh2_client/issues/8)
- [ ] Remove unnecessary dependencies:
  - Replace `basic-auth` with native HTTP authentication
  - Evaluate other dependencies for removal

#### 3.1 Module System
- [ ] Convert to ESM:
  ```javascript
  // Before
  const SSH = require('ssh2').Client
  module.exports = SSHConnection
  
  // After
  import { Client as SSH } from 'ssh2'
  export default SSHConnection
  ```
- [ ] Update import paths
- [ ] Add "type": "module" to package.json

#### 3.2 Async/Await Implementation
- [ ] Refactor SSH connection handling:
  ```javascript
  // Before
  connect(creds) {
    return new Promise((resolve, reject) => {
      this.conn.on('ready', () => {
        resolve(this.conn)
      })
    })
  }
  
  // After
  async connect(creds) {
    try {
      await this.setupConnection(creds)
      return this.conn
    } catch (error) {
      throw new SSHConnectionError(`Connection failed: ${error.message}`)
    }
  }
  ```

- [ ] Update socket event handlers:
  ```javascript
  // Before
  handleAuthenticate(creds) {
    if (isValidCredentials(creds)) {
      this.initializeConnection(creds)
        .then(() => {
          // ... success handling
        })
        .catch(err => {
          // ... error handling
        })
    }
  }
  
  // After
  async handleAuthenticate(creds) {
    try {
      if (!isValidCredentials(creds)) {
        throw new Error('Invalid credentials format')
      }
      await this.initializeConnection(creds)
      // ... success handling
    } catch (error) {
      // ... error handling
    }
  }
  ```

#### 3.3 Native API Usage
- [ ] Replace custom file operations with fs/promises:
  ```javascript
  // Before
  fs.readFile(filePath, 'utf8', (err, data) => {
    if (err) return res.status(500).send('Error')
    res.send(modifyHtml(data, config))
  })
  
  // After
  import { readFile } from 'node:fs/promises'
  
  try {
    const data = await readFile(filePath, 'utf8')
    res.send(modifyHtml(data, config))
  } catch (error) {
    res.status(500).send('Error')
  }
  ```

#### 3.4 Testing Updates
- [ ] Migrate to Node.js test runner:
  ```javascript
  // Before (Jest)
  describe('SSHConnection', () => {
    it('should connect successfully', async () => {
      expect(await sshConnection.connect(creds)).toBeDefined()
    })
  })
  
  // After (node:test)
  import test from 'node:test'
  import assert from 'node:assert/strict'
  
  test('SSHConnection', async (t) => {
    await t.test('should connect successfully', async () => {
      const connection = await sshConnection.connect(creds)
      assert.ok(connection)
    })
  })
  ```

### Phase 4: Security Enhancements
- [ ] Implement proper HTTP/2 support
- [ ] Add native crypto module usage
- [ ] Update security headers
- [ ] Implement rate limiting
- [ ] Add input validation using modern patterns

### Phase 5: Documentation and Type Safety
- [ ] Add JSDoc comments with TypeScript types
- [ ] Update API documentation
- [ ] Document new features and patterns
- [ ] Add migration guide for users

## Breaking Changes
- Node.js version requirement: 22.12.0 LTS
- Module system: ESM only
- Updated Socket.IO client requirements (webssh2_client)
- New error handling patterns
- Changed configuration format

## Migration Strategy
1. Create a new branch for modernization
2. Implement changes in phases
3. Maintain parallel support during transition
4. Add comprehensive tests
5. Document migration path for users
6. Release as major version update

## Additional Considerations
- Consider adding TypeScript support
- Evaluate WebAssembly for performance-critical parts
- Consider adding Docker multi-stage builds
- Evaluate GraphQL for API modernization

## Resources
- [Node.js 22.12.0 Documentation](https://nodejs.org/docs/latest-v22.x/api/)
- [ESM Migration Guide](https://nodejs.org/api/esm.html)
- [Node.js Test Runner Documentation](https://nodejs.org/api/test.html)

## Timeline Estimate
- Phase 1: 1 week
- Phase 2: 2 weeks
- Phase 3: 4 weeks
- Phase 4: 2 weeks
- Phase 5: 1 week

Total estimated time: 10 weeks

Please comment on this issue if you have questions or suggestions for the modernization plan.

**Comment by shirshak55** [comment]
will there be library version of it, so i can just create node server and import library?

Lastly, will there be easy way to import in React JS?

Thanks.

**Comment by aKardasz-arista** [comment]
> will there be library version of it, so i can just create node server and import library?
> 
> Lastly, will there be easy way to import in React JS?
> 
> Thanks.

Once the server is implemented, I presume making your own react frontend on top of it will be relatively trivial. You would just have to use the servers api's and display it however you please. Yes some work from having to make your own components, but I presume a lot of the html and css can probabaly just be plucked out and reactified.

**Comment by billchurch** [comment]
## Progress Update

### ✅ Phase 1: Development Environment Setup - **COMPLETE**
All tasks completed including Node.js 22 setup, ESM modules, native test runner, and GitHub Actions.

### ✅ Phase 2: Dependencies Update - **COMPLETE**
- ✅ Express updated to v5.1.0
- ✅ Socket.io updated to v4.8.1  
- ✅ SSH2 updated to v1.17
- ✅ AJV updated to v8.17.1
- ✅ webssh2_client socket.io-client updated to v4.8.1 (completed in commit billchurch/webssh2_client@09f3352)
- ✅ All major dependencies modernized in commit ce0700d

### ✅ Phase 3.1: Module System - **COMPLETE**
- ✅ Converted to ESM with `"type": "module"` in package.json
- ✅ All imports updated to ES module syntax

### ✅ Phase 3.2: Async/Await Implementation - **COMPLETE**
✅ All callback-based patterns converted to modern async/await

### 🔄 Phase 3.3: Native API Usage - **PENDING**
- Callback-based fs operations in `connectionHandler.js` need migration to `fs/promises`

### 🔄 Phase 4: Security Enhancements - **PENDING**
- [ ] Implement rate limiting
- [ ] Add HTTP/2 support
- [ ] Add security headers (helmet)
- [ ] Update input validation

### 🔄 Phase 5: Documentation and Type Safety - **IN PROGRESS**
- ✅ JSDoc comments added (198 occurrences across 15 files)
- [ ] Migration guide for users
- [ ] Complete API documentation updates

### Next Steps
1. Refactor remaining promise/callback code to async/await
2. Implement security enhancements
3. Complete documentation and migration guide

Estimated remaining work: ~4 weeks for Phases 3.2, 3.3, 4, and completion of Phase 5.

**Comment by billchurch** [comment]
## ✅ Phase 3.2 Completed: Async/Await Implementation

Successfully modernized the codebase to use async/await patterns throughout. This phase brings significant improvements to code readability and error handling.

### Changes Implemented

#### Core Refactoring
- **`app/ssh.js`**: Converted `connect()` and `shell()` methods to async/await while maintaining Promise-based implementation for compatibility
- **`app/socket.js`**: 
  - Refactored `initializeConnection()` to use async/await with try/catch blocks
  - Updated `createShell()` to async/await pattern
  - Promisified `session.save()` callback for better async handling
- **`app/connectionHandler.js`**: Migrated from callback-based `fs.readFile()` to `fs/promises` async/await

#### Testing Updates
- Fixed SSH unit tests to handle improved error differentiation (connection vs authentication errors)
- Updated socket unit tests with proper mocking for async operations
- Created comprehensive Playwright test suite (`websocket-async-auth.test.js`) covering:
  - Modal login authentication flows (`/ssh/`)
  - HTTP Basic Auth scenarios (`/ssh/host/...`)
  - Error handling and recovery
  - Session persistence
  - Terminal operations with async patterns
  - Keyboard-interactive auth handling

### Key Improvements
✅ All callback-based patterns converted to modern async/await
✅ Improved error handling with proper async context
✅ Better distinction between connection and authentication errors
✅ All unit tests passing (41 passed, 0 failed)
✅ Comprehensive functional test coverage for both auth methods
✅ Code now leverages Node.js 22's capabilities while maintaining backward compatibility

### Test Results
```
# tests 54
# suites 14  
# pass 41
# fail 0
# cancelled 0
# skipped 0
# todo 13
```

### Example Refactoring
**Before (Promise wrapper):**
```javascript
connect(creds) {
  return new Promise((resolve, reject) => {
    this.conn.on('ready', () => resolve(this.conn))
    this.conn.on('error', (err) => reject(err))
  })
}
```

**After (Async/Await):**
```javascript
async initializeConnection(creds) {
  try {
    await this.ssh.connect(creds)
    // success handling
  } catch (err) {
    // error handling
  }
}
```

The refactoring maintains full functionality while improving code readability, maintainability, and error handling. The async/await patterns make the asynchronous flow more explicit and easier to debug.

Commit: dfcde02

**Comment by shirshak55** [comment]
looks great thanks.

**Comment by aKardasz-arista** [comment]
Do these changes implement the new separation between frontend and backend? I see the new release has server in the name, for users who want to upgrade is there a path to follow if this is the case?

**Comment by billchurch** [comment]
See #406

**Comment by billchurch** [comment]
> will there be library version of it, so i can just create node server and import library?
> 
> 
> 
> Lastly, will there be easy way to import in React JS?
> 
> 
> 
> Thanks.

Hasn't been published yet,  but that is the plan.
